{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[{"file_id":"1P43VCI2OUXTw8qdnUqbCe4xcPwAJGgH3","timestamp":1729114928875}]},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["*   **Año:** 2024\n","*   **Alumno/a:** Maria Guadalupe Echeverria\n","*   **Legajo:** 141821621"],"metadata":{"id":"UwxQU5JCF33j"}},{"cell_type":"markdown","source":["# Pydantic\n","Pydantic es una libreria rapida y extensible que nos permite validar datos usando tipos de datos de Python.\n"],"metadata":{"id":"8ec8DQdbWQfC"}},{"cell_type":"markdown","source":["Primero, importe `pydantic`."],"metadata":{"id":"uF01w4AQcrtV"}},{"cell_type":"code","source":["import pydantic"],"metadata":{"id":"4WPUcwU_c5n2"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["Supongamos que tenemos una lista de clientes (llamemoslo en el codigo `Client`). Los clientes tienen dos campos: DNI (un entero) y nacionalidad (un `string`). Cree el modelo base de `Client` (en forma de clases de Python)."],"metadata":{"id":"eC8fpbQ04GzX"}},{"cell_type":"code","source":["from pydantic import BaseModel\n","\n","class Client (BaseModel):\n","  DNI: int\n","  nacionalidad : str"],"metadata":{"id":"I4zJ7s_k4GkI"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["Cree a un usuario con documento 39.755.010 y nacionalidad 'Argentina'. Muestre todos sus campos."],"metadata":{"id":"zas-XX4r4SeP"}},{"cell_type":"code","source":["class Usuario (BaseModel):\n","  DNI: int = '39.755.010'\n","  nacionalidad : str = 'Argentina'\n"],"metadata":{"id":"_DhtCWhr4ST9"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["Intente crear al usuario con un documento en forma de `string`. Deberia fallar..."],"metadata":{"id":"ejbn5RSH4S_W"}},{"cell_type":"code","source":["class Usuario (BaseModel):\n","  DNI: str = 39.755.010\n","  nacionalidad : str = 'Argentina'\n","\n","#falla"],"metadata":{"id":"OMPq8C1C4Su3","executionInfo":{"status":"error","timestamp":1732209541207,"user_tz":180,"elapsed":592,"user":{"displayName":"Guadalupe Echeverria","userId":"02418485184000041787"}},"colab":{"base_uri":"https://localhost:8080/","height":111},"outputId":"e6b1426d-a7cc-429b-aafd-3a46eae4fb18"},"execution_count":null,"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-5-076bf012ba74>, line 2)","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-5-076bf012ba74>\"\u001b[0;36m, line \u001b[0;32m2\u001b[0m\n\u001b[0;31m    DNI: str = 39.755.010\u001b[0m\n\u001b[0m                     ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"]}]},{"cell_type":"markdown","source":[],"metadata":{"id":"O5KHwRfBxdSb"}},{"cell_type":"markdown","source":["Hemos detectado que ciertos clientes tienen nacionalidades que no existen. Ademas, hay numeros de documento negativos y se tiene que poder agregar la fecha de registro de los clientes (que no pueden ser del futuro). Cambiar la definicion del cliente para que estas cosas no ocurran. Despues de la siguiente celda, cree otras 3 mas probando un caso donde deberia funcionar y otros dos en los que no."],"metadata":{"id":"jARZRMfe6MPE"}},{"cell_type":"code","source":["from pydantic import BaseModel, create_model, Field, validator\n","from typing import List\n","from datetime import date\n","\n","nacionalidades_validas = ['Argentina', 'Chile', 'Brasil', 'Uruguay', 'Paraguay']\n","class Client(BaseModel):\n","    DNI: int = Field(..., gt=0, description=\"DNI debe ser un número positivo\")\n","    nacionalidad: str\n","    fecha_registro: date\n","\n","    @validator('nacionalidad')\n","    def validar_nacionalidad(cls, value):\n","        if value not in nacionalidades_validas:\n","            raise ValueError(f'Nacionalidad {value} no es válida.')\n","        return value\n","\n","    @validator('fecha_registro')\n","    def validar_fecha_registro(cls, value):\n","        if value > date.today():\n","            print(\"error, fecha inválida:\", value)\n","        return value\n"],"metadata":{"id":"JWsWZZPH6NFv","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1732209660841,"user_tz":180,"elapsed":628,"user":{"displayName":"Guadalupe Echeverria","userId":"02418485184000041787"}},"outputId":"f3d1d43e-f50e-4653-fbfe-f9d8bb9261d2"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stderr","text":["<ipython-input-7-86db358b31f0>:11: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/\n","  @validator('nacionalidad')\n","<ipython-input-7-86db358b31f0>:17: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/\n","  @validator('fecha_registro')\n"]}]},{"cell_type":"code","source":["# Caso que funciona\n","client1 = Client(DNI=12345678, nacionalidad='Argentina', fecha_registro=date(2023,5,1))\n","print(client1)\n"],"metadata":{"id":"sWyLaqoC7QUK","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1732209689968,"user_tz":180,"elapsed":5,"user":{"displayName":"Guadalupe Echeverria","userId":"02418485184000041787"}},"outputId":"26670271-d9a0-4ab6-bd96-ffbb191fd9f5"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["DNI=12345678 nacionalidad='Argentina' fecha_registro=datetime.date(2023, 5, 1)\n"]}]},{"cell_type":"code","source":["# Caso que debería fallar (DNI negativo)\n","\n","client2 = Client(DNI=-12345678, nacionalidad=\"Argentina\", fecha_registro=date(2023, 5, 1))\n","print(client2)\n"],"metadata":{"id":"E6h_7zb77QhN","colab":{"base_uri":"https://localhost:8080/","height":388},"executionInfo":{"status":"error","timestamp":1732209728747,"user_tz":180,"elapsed":636,"user":{"displayName":"Guadalupe Echeverria","userId":"02418485184000041787"}},"outputId":"2456fb78-ce55-4419-fe32-5eebf39e545a"},"execution_count":null,"outputs":[{"output_type":"error","ename":"ValidationError","evalue":"1 validation error for Client\nDNI\n  Input should be greater than 0 [type=greater_than, input_value=-12345678, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.9/v/greater_than","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValidationError\u001b[0m                           Traceback (most recent call last)","\u001b[0;32m<ipython-input-10-2bb14fd21f96>\u001b[0m in \u001b[0;36m<cell line: 3>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Caso que debería fallar (DNI negativo)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mclient2\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mClient\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mDNI\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m-\u001b[0m\u001b[0;36m12345678\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnacionalidad\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"Argentina\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfecha_registro\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m2023\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m5\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mclient2\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/pydantic/main.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, **data)\u001b[0m\n\u001b[1;32m    210\u001b[0m         \u001b[0;31m# `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    211\u001b[0m         \u001b[0m__tracebackhide__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 212\u001b[0;31m         \u001b[0mvalidated_self\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__pydantic_validator__\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mvalidate_python\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself_instance\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    213\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mvalidated_self\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    214\u001b[0m             warnings.warn(\n","\u001b[0;31mValidationError\u001b[0m: 1 validation error for Client\nDNI\n  Input should be greater than 0 [type=greater_than, input_value=-12345678, input_type=int]\n    For further information visit https://errors.pydantic.dev/2.9/v/greater_than"]}]},{"cell_type":"code","source":["# Caso que debería fallar (fecha de registro en el futuro)\n","\n","client3 = Client(DNI=87654321, nacionalidad=\"Uruguay\", fecha_registro=date(2025, 1, 1))\n","print(client3)\n"],"metadata":{"id":"MtDGMxri7R_O","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1732209780433,"user_tz":180,"elapsed":439,"user":{"displayName":"Guadalupe Echeverria","userId":"02418485184000041787"}},"outputId":"90fd45f9-6afd-4f97-dc7b-0e29b4a717ba"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["error, fecha inválida: 2025-01-01\n","DNI=87654321 nacionalidad='Uruguay' fecha_registro=datetime.date(2025, 1, 1)\n"]}]},{"cell_type":"markdown","source":["# Pandera\n","Hacer lo que se pidio en la ultima celda anterior, pero con Pandera."],"metadata":{"id":"79P3MNuZ8-t3"}},{"cell_type":"code","source":["import pandera as pa\n","from datetime import date\n","import pandas as pd\n","\n","# Lista de países válidos\n","PAISES_VALIDOS = ['Argentina', 'Brasil', 'Chile', 'Uruguay', 'Paraguay']\n","\n","# Defino el esquema\n","cliente_schema = pa.DataFrameSchema({\n","    \"DNI\": pa.Column(int, checks=pa.Check.ge(1)),  # DNI debe ser mayor o igual a 1\n","    \"nacionalidad\": pa.Column(str, checks=pa.Check.isin(PAISES_VALIDOS)),  # Nacionalidad válida\n","    \"fecha_registro\": pa.Column(pa.DateTime, checks=pa.Check.le(date.today())),  # Fecha no puede ser futura\n","})\n","\n","# Df de prueba\n","clientes = pd.DataFrame({\n","    \"DNI\": [12345678, -23456789, 87654321],\n","    \"nacionalidad\": [\"Argentina\", \"Perú\", \"Brasil\"],\n","    \"fecha_registro\": [date(2023, 5, 1), date(2025, 1, 1), date(2022, 12, 15)]\n","})\n","\n","try:\n","    cliente_schema.validate(clientes)\n","    print(\"Datos válidos\")\n","except pa.errors.SchemaError as e:\n","    print(f\"Error en la validación: {e}\")\n","\n","\n","\n"],"metadata":{"id":"z3DJDdci8-BP","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1732211384562,"user_tz":180,"elapsed":1207,"user":{"displayName":"Guadalupe Echeverria","userId":"02418485184000041787"}},"outputId":"180482af-8d44-4c00-af5d-4528a08e5c73"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Error en la validación: Column 'DNI' failed element-wise validator number 0: greater_than_or_equal_to(1) failure cases: -23456789\n"]}]}]}